# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy new

on:
  push:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      - name: Deploy to aliyun server        # 为 step 指定一个名称，将会在 github action 的控制台中显示
        uses: easingthemes/ssh-deploy@v2.1.5      #可以访问的仓库，实现的上传服务器步骤被封装在此action
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}  #这个是阿里云的私钥
          ARGS: "-avzr --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}    #阿里云的 ip
          REMOTE_USER: ${{ secrets.SERVER_USER }}    #阿里云用户
          TARGET: "/www/html/deploy-test"       #被部署的服务器路径 


  
