# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy new

on:
  push:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      - name: SCP to Aliyun ECS        # 为 step 指定一个名称，将会在 github action 的控制台中显示
        uses: srueda99/scp-action@v12
        with:
          # Port for SCP
          #port: # optional, default is 22
          # IP Address or DNS of your target host
          host: ${{ vars.SERVER_HOST }}    #阿里云的 ip
          # Source route folder
          origin: "./"
          # Destination route folder
          destination: "/www/html/deploy-test"       #被部署的服务器路径 
          # User for remote connection
          username: ${{ vars.SERVER_USER }}    #阿里云用户
          # Password for the user
          #password: # optional
          # Private SSH key
          key: ${{ secrets.PRIVATE_KEY }}  #这个是阿里云的私钥
          # Passphrase for SSH key
          #passphrase: # optional
